spring:
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        new_generator_mappings: false
        format_sql: true
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext

#    datasource:
#      url: jdbc:mysql://localhost:3306/test?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC";
#      username: root
#      password: 123456
#      driver-class-name: com.mysql.cj.jdbc.Driver
#spring.datasource.dr